# Project Overview
author: Victor Rabêllo
squad: Bella-Insights

# Model Name
model_name: houses_regression_model.pkl

# AWS Resources
bucket_name: testebella
train_features_file_name: houses_train.csv
test_features_file_name: houses_test.csv
train_features_save_name: houses_train_features.csv
target_feature_save_name: houses_target.csv

# Variables
target: SalePrice

# Selected Model Features
selected_features:
  - HouseStyle
  - BsmtFinType1
  - MiscVal
  - LotArea
  - LotFrontage
  - SalePrice

selected_features_pipeline:
  - HouseStyle
  - BsmtFinType1
  - MiscVal
  - LotArea
  - LotFrontage

# Numeric Features
numeric_features:
  - MiscVal
  - LotArea
  - LotFrontage

# Scaled Features
scaled_features:
  - ScaledMiscVal
  - ScaledLotArea
  - ScaledLotFrontage

# Dropping Unused Features
to_drop_unused_features:
  - HouseStyle
  - BsmtFinType1
  - NewHouseStyle

# House Style Variable
house_style: HouseStyle
new_house_style: NewHouseStyle
one_story: 1Story
two_story: 2Story
other_house_style: other

# Other Variables
bsm_type_1: BsmtFinType1
lot_frontage: LotFrontage

# Merge How Method
left_merge: left

# Data Split Configuration
test_size: 0.25
random_state: 16

# Model Configuration
n_estimators: 400
model_random_state: 16

# Features Dict Split
x_train: X_train
x_test: X_test
y_train: y_train
y_test: y_test

# Features Dict Train Keys
model_key: model
train_mae: train_mae
test_mae: test_mae
