#!/usr/bin/env python

from __future__ import print_function

import os
import pickle
import sys


# The function to execute the training.
# TODO: REFACTOR THIS FUNCTION
def train():
    """

    Returns
    -------

    """
    processed_train_data = utils.filter_dataframe(
        data_manager.load_dataset(
            file_name=config.app_config.latest_train_data, raw_data=False
        )
    )

    trained_model_data_dict = modelling.processed_training_model(processed_train_data)

    model = trained_model_data_dict[config.app_config.model_data_model]

    # TODO: CREATE MODEL TIMESTAMP AND LATEST
    with open(os.path.join(model_path, 'catboost-model.pkl'), 'wb') as out:
        pickle.dump(model, out)
    print('Training complete.')


if __name__ == '__main__':
    train()

    # A zero exit code causes the job to be marked a Succeeded.
    sys.exit(0)
